version: '2'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openml
    network_mode: bridge

  elasticsearch:
    image: elasticsearch:5
    network_mode: bridge

  website:
    build: ./apache
    ports:
      - 3000:80
    links:
      - mysql:mysql
      - elasticsearch:elasticsearch
    env_file:
      - ./common.env
    network_mode: bridge

networks:
  default:
    external:
      name: bridge
